apiVersion: apps/v1
kind: Deployment
metadata:
  name: dimension-website
  labels:
    app: dimension-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dimension-website
  template:
    metadata:
      labels:
        app: dimension-website
    spec:
      containers:
      - name: dimension-website
        image: hazemsoliman9/dimension-website
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dimension-website-svc
spec:
  ports:
  - port: 80
  selector:
    app: dimension-website
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dimension-website-ingress
  labels:
    name: dimension-website-ingress
  namespace: hazem-namespace
spec:
  rules:
  - host: demo.dimensionwebsite.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: dimension-website-svc
            port: 
              number: 80
