apiVersion: apps/v1
kind: Deployment
metadata:
  name: dimension-website
  labels:
    app: dimension-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dimension-website
  template:
    metadata:
      labels:
        app: dimension-website
    spec:
      containers:
      - name: dimension-website
        image: hazemsoliman9/dimension-website
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dimension-website-public-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: dimension-website
