name: CI
# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build and Push Docker Image 
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: hazemsoliman9/dimension-website
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
       
      - name: Azure Login
        uses: azure/actions/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v1
        with:        
        # Path to the manifest files which will be used for deployment.
          manifests: |
            dimensionwebsite-deployment.yaml
          
          action: deploy
       
#      - name: SonarQube Scan
#        uses: kitabisa/sonarqube-action@v1.2.0
#        with:
#          host: ${{ secrets.SONARQUBE_HOST }}
#          login: ${{ secrets.SONARQUBE_TOKEN }}
